AWSTemplateFormatVersion: '2010-09-09'
Description: ALBs para entornos DEV y PDN

Parameters:
  NetworkUser:
    Type: String
    Description: Nombre del usuario de red
    Default: pfrias
  ExistingVPCId:
    Type: AWS::EC2::VPC::Id
    Description: ID de la VPC existente
  PublicSubnetAZ1Id:
    Type: AWS::EC2::Subnet::Id
    Description: ID de la subnet publica en AZ1
  PublicSubnetAZ2Id:
    Type: AWS::EC2::Subnet::Id
    Description: ID de la subnet publica en AZ2

Resources:
  ALBDEV:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub LDC-AUTH-ALB-${NetworkUser}-DEV
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnetAZ1Id
        - !Ref PublicSubnetAZ2Id
      SecurityGroups:
        - !ImportValue
          Fn::Sub: LDC-AUTH-SG-${NetworkUser}-DEV
      Tags:
        - Key: Name
          Value: !Sub LDC-AUTH-ALB-${NetworkUser}-DEV

  ALBPDN:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Name: !Sub LDC-AUTH-ALB-${NetworkUser}-PDN
      Scheme: internet-facing
      Subnets:
        - !Ref PublicSubnetAZ1Id
        - !Ref PublicSubnetAZ2Id
      SecurityGroups:
        - !ImportValue
          Fn::Sub: LDC-AUTH-SG-${NetworkUser}-PDN
      Tags:
        - Key: Name
          Value: !Sub LDC-AUTH-ALB-${NetworkUser}-PDN

  TargetGroupBackend:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub tg-backend-${NetworkUser}
      Port: 8080
      Protocol: HTTP
      VpcId: !Ref ExistingVPCId
      TargetType: instance

  TargetGroupFrontend:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: !Sub tg-frontend-${NetworkUser}
      Port: 80
      Protocol: HTTP
      VpcId: !Ref ExistingVPCId
      TargetType: instance

  ALBListener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupFrontend
      LoadBalancerArn: !Ref ALBDEV
      Port: 80
      Protocol: HTTP

  ALBListenerRuleBackend:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALBListener
      Priority: 1
      Conditions:
        - Field: path-pattern
          Values:
            - /api/*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroupBackend

Outputs:
  ALBDEV:
    Value: !Ref ALBDEV
    Export:
      Name: !Sub LDC-AUTH-ALB-${NetworkUser}-DEV
  ALBPDN:
    Value: !Ref ALBPDN
    Export:
      Name: !Sub LDC-AUTH-ALB-${NetworkUser}-PDN